import { StyleSheet } from 'react-native';

export const createStyles = (colors) =>  
  StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    backgroundColor: colors.navy,
    padding: 24,
    width: 240,
  },
  sidebarBrand: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  sidebarCaption: {
    color: '#BFE9D5',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 5,
  },
  sidebarMenu: {
    gap: 8,
    marginTop: 48,
  },
  sidebarMenuItem: {
    alignItems: 'center',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 12,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  sidebarMenuItemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
  },
  sidebarMenuIcon: {
    color: '#BFE9D5',
    fontSize: 18,
  },
  sidebarMenuText: {
    color: '#CBD5E1',
    fontSize: 14,
    fontWeight: '800',
  },
  sidebarMenuTextActive: {
    color: '#FFFFFF',
  },
  mobileNavigation: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 10,
    paddingTop: 8,
  },
  mobileNavigationItem: {
    alignItems: 'center',
    gap: 3,
    minWidth: 76,
    paddingVertical: 4,
  },
  mobileNavigationIcon: {
    color: colors.muted,
    fontSize: 18,
  },
  mobileNavigationIconActive: {
    color: colors.green,
  },
  mobileNavigationText: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  mobileNavigationTextActive: {
    color: colors.green,
  },
  container: {
    flex: 1,
  },
  listContent: {
    padding: 24,
    paddingBottom: 44,
  },
  headerContent: {
    gap: 22,
  },
  hero: {
  backgroundColor: colors.navy,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: colors.line,
  padding: 22,
  gap: 12,
  shadowColor: '#101828',
  shadowOffset: { width: 0, height: 12 },
  shadowOpacity: 0.18,
  shadowRadius: 16,
  elevation: 5,
 },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroEyebrow: {
  color: '#BFE9D5',
  fontSize: 12,
  fontWeight: '900',
  textTransform: 'uppercase',
  },
heroChip: {
  alignSelf: 'flex-start',
  backgroundColor: colors.inputBg,
  borderRadius: 999,
  color: colors.ink,
  fontSize: 12,
  fontWeight: '900',
  overflow: 'hidden',
  paddingHorizontal: 12,
  paddingVertical: 5,
  },
heroTitle: {
  color: '#FFFFFF',
  fontSize: 28,
  fontWeight: '900',
  lineHeight: 34,
  },
  heroSubtitle: {
  color: '#D7DEE8',
  fontSize: 14,
  fontWeight: '700',
  lineHeight: 21,
  },
  heroActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heroAction: {
    backgroundColor: colors.green,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  heroActionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  themeToggle: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  themeToggleText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  panel: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 16,
    shadowColor: colors.navy,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  editingPanel: {
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderWidth: 2,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 18,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  datePreview: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '900',
  },
  inputLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 2,
  },

  // Penginputan Banking data picker
  input: {
  minHeight: 56,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: colors.line,
  backgroundColor: colors.inputBg,
  paddingHorizontal: 16,
  color: colors.ink,
  fontSize: 15,
  fontWeight: '700',
},

  bankingDatePicker: {
  backgroundColor: colors.inputBg,
  borderColor: colors.line,
  borderRadius: 8,
  borderWidth: 1,
  padding: 8,
},
bankingDateButton: {
  alignItems: 'center',
  backgroundColor: colors.card,
  borderColor: colors.line,
  borderRadius: 8,
  borderWidth: 1,
  flexDirection: 'row',
  justifyContent: 'space-between',
  minHeight: 54,
  paddingHorizontal: 12,
},
////////////////////////

  bankingDateLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 3,
  },
  bankingDateValue: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  bankingDateIcon: {
    color: colors.green,
    fontSize: 14,
    fontWeight: '900',
  },
  dateModalOverlay: {
    backgroundColor: 'rgba(16, 42, 67, 0.34)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  dateModalBackdrop: {
    flex: 1,
  },
  dateModalSheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    gap: 12,
    maxHeight: '72%',
    padding: 16,
  },
  dateModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateModalTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  dateModalClose: {
    color: colors.green,
    fontSize: 13,
    fontWeight: '900',
  },
  dateModalPreview: {
    backgroundColor: colors.greenSoft,
    borderColor: colors.green,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.green,
    fontSize: 13,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlign: 'center',
  },
  dateOptionColumns: {
    flexDirection: 'row',
    gap: 8,
  },
  dateOptionColumn: {
    flex: 1,
    gap: 6,
  },
  dateOptionTitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  dateOptionList: {
    backgroundColor: colors.inputBg,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    maxHeight: 190,
    padding: 5,
  },
  dateOptionItem: {
    alignItems: 'center',
    borderRadius: 8,
    minHeight: 34,
    justifyContent: 'center',
    marginBottom: 4,
  },
  dateOptionItemActive: {
    backgroundColor: colors.green,
  },
  dateOptionText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  dateOptionTextActive: {
    color: '#FFFFFF',
  },
  dateModalActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  dateTodayButton: {
    alignItems: 'center',
    backgroundColor: colors.greenSoft,
    borderColor: colors.green,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 44,
    justifyContent: 'center',
  },
  dateTodayButtonText: {
    color: colors.green,
    fontSize: 14,
    fontWeight: '900',
  },
  dateApplyButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 8,
    flex: 1,
    minHeight: 44,
    justifyContent: 'center',
  },
  dateApplyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  summaryWrap: {
    gap: 10,
  },
  balanceCard: {
    backgroundColor: colors.greenSoft,
    borderColor: colors.green,
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  balanceLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  balanceAmount: {
    color: colors.green,
    fontSize: 24,
    fontWeight: '900',
  },
  balanceAmountDanger: {
    color: colors.red,
    fontSize: 24,
    fontWeight: '900',
  },
  balanceStatus: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 6,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
summaryItemIncome: {
  flexBasis: '48%',
  flexGrow: 1,
  borderRadius: 8,
  backgroundColor: colors.greenSoft,
  borderColor: colors.green,
  borderWidth: 1,
  padding: 12,
},
summaryItemExpense: {
  flexBasis: '48%',
  flexGrow: 1,
  borderRadius: 8,
  backgroundColor: colors.redSoft,
  borderColor: colors.red,
  borderWidth: 1,
  padding: 12,
},
incomeText: {
  color: colors.green,
  fontSize: 15,
  fontWeight: '900',
},
expenseText: {
  color: colors.red,
  fontSize: 15,
  fontWeight: '900',
},

  balanceText: {
    color: colors.green,
    fontSize: 18,
    fontWeight: '900',
  },
  walletSummary: {
    backgroundColor: colors.inputBg,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  walletTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  walletRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  walletName: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  walletAmount: {
    color: colors.green,
    fontSize: 13,
    fontWeight: '900',
  },
  segmentedControl: {
    backgroundColor: colors.inputBg,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    padding: 8,
  },
  segment: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActiveIncome: {
    backgroundColor: colors.green,
    borderColor: colors.green,
  },
  segmentActiveExpense: {
    backgroundColor: colors.red,
    borderColor: colors.red,
  },
  segmentText: {
    color: colors.muted,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  categoryWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 9,
  },
  categoryButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.inputBg,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryActive: {
    backgroundColor: colors.navy,
    borderColor: colors.green,
  },
  categoryText: {
    color: colors.muted,
    fontWeight: '800',
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  primaryButton: {
  minHeight: 50,
  borderRadius: 8,
  backgroundColor: colors.navy,
  alignItems: 'center',
  justifyContent: 'center',
  shadowColor: colors.navy,
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.18,
  shadowRadius: 10,
  elevation: 3,
},

  primaryButtonDisabled: {
    backgroundColor: '#9FB0BB',
    shadowOpacity: 0,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryButton: {
  minHeight: 46,
  borderRadius: 8,
  borderColor: colors.line,
  borderWidth: 1,
  backgroundColor: colors.card,
  alignItems: 'center',
  justifyContent: 'center',
},
secondaryButtonText: {
  color: colors.muted,
  fontSize: 15,
  fontWeight: '900',
  },
  listTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '900',
    marginTop: 6,
  },
  transactionItem: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    overflow: 'hidden',
    shadowColor: colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  transactionAccentIncome: {
    backgroundColor: colors.green,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 5,
  },
  transactionAccentExpense: {
    backgroundColor: colors.red,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 5,
  },
  transactionMeta: {
    flex: 1,
    gap: 4,
    paddingLeft: 4,
  },
  transactionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  transactionNote: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  transactionCategory: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  transactionAmountWrap: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 4,
    maxWidth: '44%',
  },
  deleteHint: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  typeBadgeIncome: {
    backgroundColor: colors.greenSoft,
    borderRadius: 8,
    color: colors.green,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  typeBadgeExpense: {
    backgroundColor: colors.redSoft,
    borderRadius: 8,
    color: colors.red,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  smallBadgeIncome: {
    backgroundColor: colors.greenSoft,
    borderRadius: 8,
    color: colors.green,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  smallBadgeExpense: {
    backgroundColor: colors.redSoft,
    borderRadius: 8,
    color: colors.red,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  emptyState: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    padding: 18,
    alignItems: 'center',
  },
  emptyBadge: {
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    marginBottom: 10,
    width: 38,
  },
  emptyBadgeText: {
    color: colors.muted,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  emptyText: {
    color: colors.muted,
    marginTop: 4,
  },
  chartPeakText: {
    color: '#D94841',
    fontSize: 12,
    fontWeight: '900',
  },
  
  
  chartPeriodWrap: {
    backgroundColor: colors.inputBg,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    padding: 5,
  },
  chartPeriodButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    minHeight: 36,
    justifyContent: 'center',
  },
  chartPeriodButtonActive: {
    backgroundColor: colors.navy,
  },
  chartPeriodText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  chartPeriodTextActive: {
    color: '#FFFFFF',
  },
  chartStatsRow: {
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 18,
    paddingBottom: 12,
  },
  chartStat: {
    flex: 1,
    gap: 4,
  },
  chartStatLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  chartStatValue: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  heatList: {
  backgroundColor: colors.inputBg,
  borderColor: colors.line,
  borderRadius: 8,
  borderWidth: 1,
  marginTop: 4,
  gap: 6,
  padding: 10,
  },

  heatRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 34,
  },
  heatDateWrap: {
    width: 42,
  },
  heatDate: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  heatDatePeak: {
    color: '#D94841',
  },
  heatTrack: {
  backgroundColor: colors.line,
  borderRadius: 999,
  flex: 1,
  height: 22,
  justifyContent: 'center',
  overflow: 'hidden',
  position: 'relative',
},
heatBar: {
  backgroundColor: '#E58A77',
  borderRadius: 999,
  height: '100%',
  minWidth: 0,
  },

  heatBarPeak: {
    backgroundColor: '#D94841',
  },
  heatValueWrap: {
    alignItems: 'flex-end',
    width: 76,
  },
  heatValue: {
    color: colors.ink,
    fontSize: 11,
    fontWeight: '900',
  },
  heatValueMuted: {
    color: '#B1BDC3',
  },
  heatPeakBadge: {
    backgroundColor: colors.card,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    position: 'absolute',
    right: 4,
  },
  heatPeakBadgeText: {
    color: '#D94841',
    fontSize: 9,
    fontWeight: '900',
  },
  heatEmptyNotice: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
  },
  heatEmptyText: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },

  reportToolsHeader: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    paddingBottom: 14,
  },
  reportToolsCaption: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  reportToolsGrid: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
  },
  reportToolColumn: {
    flex: 1,
    gap: 14,
    minWidth: 280,
  },
  reportToolDivider: {
    alignSelf: 'stretch',
    backgroundColor: colors.line,
    minHeight: 132,
    width: 1,
  },
  reportToolHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  reportToolTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  reportToolDot: {
    backgroundColor: colors.green,
    borderRadius: 999,
    height: 9,
    width: 9,
  },
  reportToolTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  reportToolBadge: {
    backgroundColor: colors.greenSoft,
    borderRadius: 999,
    color: colors.green,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  exportActionRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  exportPeriodWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  exportPeriodButton: {
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  exportPeriodButtonActive: {
    backgroundColor: colors.navy,
    borderColor: colors.navy,
  },
  exportPeriodText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  exportPeriodTextActive: {
    color: '#FFFFFF',
  },
  exportSelectWrap: {
    alignSelf: 'flex-start',
    position: 'relative',
    width: 180,
    zIndex: 10,
  },
  exportSelect: {
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 42,
    paddingHorizontal: 14,
  },
  exportSelectText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  exportSelectIcon: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: '900',
  },
  exportMenu: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    marginTop: 8,
    padding: 6,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  exportMenuOption: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  exportMenuOptionActive: {
    backgroundColor: colors.navy,
  },
  exportMenuText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  exportMenuTextActive: {
    color: '#FFFFFF',
  },
  exportActionButton: {
    minHeight: 42,
    minWidth: 132,
    paddingHorizontal: 16,
  },
  exportActionText: {
    fontSize: 13,
  },
  filterTrigger: {
    alignItems: 'center',
    backgroundColor: colors.greenSoft,
    borderColor: colors.green,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 72,
    padding: 14,
  },
  filterTriggerLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  filterTriggerValue: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 3,
  },
  filterTriggerBadge: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  filterTriggerBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  filterModalOverlay: {
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  filterModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  filterModalCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    gap: 16,
    padding: 20,
  },
  filterModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterModalTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  filterModalSubtitle: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 4,
  },
  filterModalClose: {
    color: colors.green,
    fontSize: 13,
    fontWeight: '900',
  },
  filterModalSection: {
    gap: 8,
  },
  filterModalLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  filterModalApply: {
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 46,
  },
  filterModalApplyText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  listSegmentWrap: {
    alignSelf: 'stretch',
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    padding: 5,
  },
  listSegmentButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexBasis: '30%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  listSegmentButtonActive: {
    backgroundColor: colors.navy,
  },
  listSegmentText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  listSegmentTextActive: {
    color: '#FFFFFF',
  },
  monthPickerWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  monthPickerButton: {
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  monthPickerButtonActive: {
    backgroundColor: colors.navy,
    borderColor: colors.navy,
  },
  monthPickerText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  monthPickerTextActive: {
    color: '#FFFFFF',
  },
  rangeExportWrap: {
    gap: 10,
  },
  rangeExportField: {
    gap: 8,
  },

});
