import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F7FA',
  },
  container: {
    flex: 1,
  },
  listContent: {
    padding: 16,
    paddingBottom: 34,
  },
  headerContent: {
    gap: 14,
  },
  hero: {
    backgroundColor: '#102A43',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1F3A5F',
    padding: 20,
    gap: 12,
    shadowColor: '#102A43',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 5,
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroEyebrow: {
    color: '#6EE7D8',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroChip: {
    backgroundColor: '#FFE8A3',
    borderRadius: 999,
    color: '#102A43',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 33,
  },
  heroSubtitle: {
    color: '#CFE8F3',
    fontSize: 14,
    fontWeight: '700',
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E1E8ED',
    padding: 16,
    gap: 12,
    shadowColor: '#1B2A38',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 2,
  },
  editingPanel: {
    borderColor: '#FCA311',
    borderWidth: 2,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    color: '#1B2A38',
    fontSize: 16,
    fontWeight: '900',
  },
  datePreview: {
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '900',
  },
  inputLabel: {
    color: '#667987',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: -6,
  },
  input: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D8E3EA',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    color: '#1B2A38',
    fontSize: 15,
    fontWeight: '700',
  },
  summaryWrap: {
    gap: 10,
  },
  balanceCard: {
    backgroundColor: '#ECFDF7',
    borderColor: '#BFEADD',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  balanceLabel: {
    color: '#4D756B',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  balanceAmount: {
    color: '#0F766E',
    fontSize: 24,
    fontWeight: '900',
  },
  balanceAmountDanger: {
    color: '#D94841',
    fontSize: 24,
    fontWeight: '900',
  },
  balanceStatus: {
    color: '#5C756E',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 6,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryItemIncome: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: 8,
    backgroundColor: '#F3FBF8',
    borderColor: '#D4F0E6',
    borderWidth: 1,
    padding: 12,
  },
  summaryItemExpense: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: 8,
    backgroundColor: '#FFF6F4',
    borderColor: '#F5D6D2',
    borderWidth: 1,
    padding: 12,
  },
  summaryLabel: {
    color: '#667987',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  incomeText: {
    color: '#0F766E',
    fontSize: 15,
    fontWeight: '800',
  },
  expenseText: {
    color: '#D94841',
    fontSize: 15,
    fontWeight: '800',
  },
  balanceText: {
    color: '#0F766E',
    fontSize: 18,
    fontWeight: '900',
  },
  segmentedControl: {
    backgroundColor: '#EEF4F7',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    padding: 5,
  },
  segment: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActiveIncome: {
    backgroundColor: '#0F766E',
    borderColor: '#0F766E',
  },
  segmentActiveExpense: {
    backgroundColor: '#D94841',
    borderColor: '#D94841',
  },
  segmentText: {
    color: '#516877',
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  categoryWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D8E3EA',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryActive: {
    backgroundColor: '#102A43',
    borderColor: '#102A43',
  },
  categoryText: {
    color: '#516877',
    fontWeight: '800',
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: '#0F766E',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F766E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryButtonDisabled: {
    backgroundColor: '#9FB0BB',
    shadowOpacity: 0,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 8,
    borderColor: '#D8E3EA',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#516877',
    fontSize: 15,
    fontWeight: '900',
  },
  listTitle: {
    color: '#1B2A38',
    fontSize: 17,
    fontWeight: '900',
    marginTop: 6,
  },
  transactionItem: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E1E8ED',
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    overflow: 'hidden',
    shadowColor: '#1B2A38',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  transactionAccentIncome: {
    backgroundColor: '#0F766E',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 5,
  },
  transactionAccentExpense: {
    backgroundColor: '#D94841',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 5,
  },
  transactionMeta: {
    flex: 1,
    gap: 4,
    paddingLeft: 4,
  },
  transactionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  transactionNote: {
    color: '#1B2A38',
    fontSize: 15,
    fontWeight: '800',
  },
  transactionCategory: {
    color: '#667987',
    fontSize: 13,
    fontWeight: '700',
  },
  transactionAmountWrap: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 4,
    maxWidth: '44%',
  },
  deleteHint: {
    color: '#90A1AD',
    fontSize: 11,
    fontWeight: '700',
  },
  typeBadgeIncome: {
    backgroundColor: '#ECFDF7',
    borderRadius: 8,
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  typeBadgeExpense: {
    backgroundColor: '#FFF0ED',
    borderRadius: 8,
    color: '#D94841',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  smallBadgeIncome: {
    backgroundColor: '#ECFDF7',
    borderRadius: 8,
    color: '#0F766E',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  smallBadgeExpense: {
    backgroundColor: '#FFF0ED',
    borderRadius: 8,
    color: '#D94841',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  emptyState: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E1E8ED',
    backgroundColor: '#FFFFFF',
    padding: 18,
    alignItems: 'center',
  },
  emptyBadge: {
    alignItems: 'center',
    backgroundColor: '#EEF4F7',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    marginBottom: 10,
    width: 38,
  },
  emptyBadgeText: {
    color: '#667987',
    fontSize: 18,
    fontWeight: '900',
  },
  emptyTitle: {
    color: '#1B2A38',
    fontSize: 15,
    fontWeight: '900',
  },
  emptyText: {
    color: '#667987',
    marginTop: 4,
  },
  chartPeakText: {
    color: '#D94841',
    fontSize: 12,
    fontWeight: '900',
  },
  chartStatsRow: {
    borderBottomColor: '#EEF4F7',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 18,
    paddingBottom: 12,
  },
  chartStat: {
    flex: 1,
    gap: 4,
  },
  chartStatLabel: {
    color: '#667987',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  chartStatValue: {
    color: '#1B2A38',
    fontSize: 16,
    fontWeight: '900',
  },
  heatList: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E1E8ED',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 4,
    gap: 6,
    padding: 10,
  },
  heatRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 34,
  },
  heatDateWrap: {
    width: 42,
  },
  heatDate: {
    color: '#667987',
    fontSize: 11,
    fontWeight: '900',
  },
  heatDatePeak: {
    color: '#D94841',
  },
  heatTrack: {
    backgroundColor: '#EAF0F3',
    borderRadius: 999,
    flex: 1,
    height: 22,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  heatBar: {
    backgroundColor: '#F08A7F',
    borderRadius: 999,
    height: '100%',
    minWidth: 0,
  },
  heatBarPeak: {
    backgroundColor: '#D94841',
  },
  heatValueWrap: {
    alignItems: 'flex-end',
    width: 76,
  },
  heatValue: {
    color: '#1B2A38',
    fontSize: 11,
    fontWeight: '900',
  },
  heatValueMuted: {
    color: '#B1BDC3',
  },
  heatPeakBadge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    position: 'absolute',
    right: 4,
  },
  heatPeakBadgeText: {
    color: '#D94841',
    fontSize: 9,
    fontWeight: '900',
  },
  heatEmptyNotice: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E1E8ED',
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
  },
  heatEmptyText: {
    color: '#90A1AD',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },

  exportPeriodWrap: {
    backgroundColor: '#EEF4F7',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    padding: 5,
  },
  exportPeriodButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  exportPeriodButtonActive: {
    backgroundColor: '#102A43',
  },
  exportPeriodText: {
    color: '#516877',
    fontSize: 13,
    fontWeight: '900',
  },
  exportPeriodTextActive: {
    color: '#FFFFFF',
  },

});
