import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#EEF3F6',
  },
  container: {
    flex: 1,
  },
  listContent: {
    padding: 18,
    paddingBottom: 36,
  },
  headerContent: {
    gap: 16,
  },
  hero: {
    backgroundColor: '#14213D',
    borderRadius: 8,
    padding: 18,
    gap: 10,
    shadowColor: '#14213D',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 4,
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroEyebrow: {
    color: '#9FD8CB',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroChip: {
    backgroundColor: '#FCA311',
    borderRadius: 8,
    color: '#14213D',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 34,
  },
  heroSubtitle: {
    color: '#C9D6DF',
    fontSize: 14,
    fontWeight: '600',
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D8E2E7',
    padding: 16,
    gap: 12,
    shadowColor: '#10212B',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    color: '#172126',
    fontSize: 16,
    fontWeight: '900',
  },
  datePreview: {
    color: '#146C94',
    fontSize: 12,
    fontWeight: '900',
  },
  inputLabel: {
    color: '#5A6D76',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: -6,
  },
  input: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#C9D6DF',
    backgroundColor: '#F8FBFC',
    paddingHorizontal: 14,
    color: '#172126',
    fontSize: 15,
    fontWeight: '700',
  },
  summaryWrap: {
    gap: 10,
  },
  balanceCard: {
    backgroundColor: '#EAF7F2',
    borderColor: '#C6E8DA',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  balanceLabel: {
    color: '#527166',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  balanceAmount: {
    color: '#0E7A4F',
    fontSize: 24,
    fontWeight: '900',
  },
  balanceAmountDanger: {
    color: '#C43D32',
    fontSize: 24,
    fontWeight: '900',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryItemIncome: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: 8,
    backgroundColor: '#F7FBF9',
    borderColor: '#D9EFE5',
    borderWidth: 1,
    padding: 12,
  },
  summaryItemExpense: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: 8,
    backgroundColor: '#FFF7F6',
    borderColor: '#F2D2CE',
    borderWidth: 1,
    padding: 12,
  },
  summaryLabel: {
    color: '#647780',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  incomeText: {
    color: '#0E7A4F',
    fontSize: 15,
    fontWeight: '800',
  },
  expenseText: {
    color: '#C43D32',
    fontSize: 15,
    fontWeight: '800',
  },
  balanceText: {
    color: '#146C94',
    fontSize: 18,
    fontWeight: '900',
  },
  segmentedControl: {
    backgroundColor: '#EEF3F6',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    padding: 5,
  },
  segment: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActiveIncome: {
    backgroundColor: '#0E7A4F',
    borderColor: '#0E7A4F',
  },
  segmentActiveExpense: {
    backgroundColor: '#C43D32',
    borderColor: '#C43D32',
  },
  segmentText: {
    color: '#49616D',
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  categoryWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#C9D6DF',
    backgroundColor: '#F8FBFC',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryActive: {
    backgroundColor: '#14213D',
    borderColor: '#14213D',
  },
  categoryText: {
    color: '#49616D',
    fontWeight: '800',
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: '#14213D',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#14213D',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  listTitle: {
    color: '#172126',
    fontSize: 17,
    fontWeight: '900',
    marginTop: 6,
  },
  transactionItem: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDE4E8',
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    overflow: 'hidden',
    shadowColor: '#10212B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  transactionAccentIncome: {
    backgroundColor: '#0E7A4F',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 5,
  },
  transactionAccentExpense: {
    backgroundColor: '#C43D32',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 5,
  },
  transactionMeta: {
    flex: 1,
    gap: 4,
    paddingLeft: 4,
  },
  transactionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  transactionNote: {
    color: '#172126',
    fontSize: 15,
    fontWeight: '800',
  },
  transactionCategory: {
    color: '#647780',
    fontSize: 13,
    fontWeight: '700',
  },
  transactionAmountWrap: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 4,
    maxWidth: '44%',
  },
  deleteHint: {
    color: '#87969D',
    fontSize: 11,
    fontWeight: '700',
  },
  typeBadgeIncome: {
    backgroundColor: '#EAF7F2',
    borderRadius: 8,
    color: '#0E7A4F',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  typeBadgeExpense: {
    backgroundColor: '#FFF0EE',
    borderRadius: 8,
    color: '#C43D32',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  smallBadgeIncome: {
    backgroundColor: '#EAF7F2',
    borderRadius: 8,
    color: '#0E7A4F',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  smallBadgeExpense: {
    backgroundColor: '#FFF0EE',
    borderRadius: 8,
    color: '#C43D32',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  emptyState: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDE4E8',
    backgroundColor: '#FFFFFF',
    padding: 18,
    alignItems: 'center',
  },
  emptyBadge: {
    alignItems: 'center',
    backgroundColor: '#EEF3F6',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    marginBottom: 10,
    width: 38,
  },
  emptyBadgeText: {
    color: '#647780',
    fontSize: 18,
    fontWeight: '900',
  },
  emptyTitle: {
    color: '#172126',
    fontSize: 15,
    fontWeight: '900',
  },
  emptyText: {
    color: '#647780',
    marginTop: 4,
  },
});
